[MWRAPPER-80] POC support maven-mvnd in only-mvnw, do not verify distributionSha256Sum now

diff --git a/maven-wrapper-distribution/src/resources/only-mvnw b/maven-wrapper-distribution/src/resources/only-mvnw
--- a/maven-wrapper-distribution/src/resources/only-mvnw
+++ b/maven-wrapper-distribution/src/resources/only-mvnw
@@ -95,23 +95,63 @@ while IFS="=" read -r key value; do
   esac
 done < "${0%/*}/.mvn/wrapper/maven-wrapper.properties"
 [ -n "${distributionUrl-}" ] || die "cannot read distributionUrl property in ${0%/*}/.mvn/wrapper/maven-wrapper.properties"
-[ -z "${MVNW_REPOURL-}" ] || distributionUrl="$MVNW_REPOURL/org/apache/maven/${distributionUrl#*/org/apache/maven/}"
+
+_MVNW_USE_MVND=false
+case "${distributionUrl##*/}" in
+(maven-mvnd-*bin.*)
+  _MVNW_USE_MVND=true
+  MVN_CMD=mvnd
+  case "$(uname -a)" in
+  (CYGWIN*|MINGW*) distributionPlatform=windows-amd64; MVN_CMD=mvnd.exe ;;
+  (Darwin*x86_64) distributionPlatform=darwin-amd64 ;;
+  (Darwin*arm64) distributionPlatform=darwin-aarch64 ;;
+  (Linux*) distributionPlatform=linux-amd64 ;;
+  (*) echo "Cannot detect native platform for mvnd on $(uname)-$(uname -m), use pure java version" >&2
+      distributionPlatform=linux-amd64
+      MVN_CMD=mvnd.sh
+      ;;
+  esac
+  distributionUrl="${distributionUrl%-bin.*}-$distributionPlatform.zip"
+  distributionUrlName="${distributionUrl##*/}"
+  distributionUrlNameMain="${distributionUrlName%.*}"
+  ;;
+(maven-mvnd-*)
+  _MVNW_USE_MVND=true
+  distributionUrlName="${distributionUrl##*/}"
+  distributionUrlNameMain="${distributionUrlName%.*}"
+  MVN_CMD=mvnd
+  ;;
+(*) [ -z "${MVNW_REPOURL-}" ] || distributionUrl="$MVNW_REPOURL/org/apache/maven/${distributionUrl#*/org/apache/maven/}"
+    distributionUrlName="${distributionUrl##*/}"
+    distributionUrlNameMain="${distributionUrlName%-bin.*}"
+    MVN_CMD="mvn${0##*/mvnw}"
+    ;;
+esac
 
 # calculate MAVEN_HOME, pattern ~/.m2/wrapper/dists/apache-maven-<version>/<hash>
-distributionUrlName="${distributionUrl##*/}"
-distributionUrlNameMain="${distributionUrlName%-bin.*}"
 MAVEN_HOME="$HOME/.m2/wrapper/dists/${distributionUrlNameMain-}/$(hash_string "$distributionUrl")"
-MVN_CMD="mvn${0##*/mvnw}"
+
+exec_maven() {
+  if $_MVNW_USE_MVND && [ "$MVN_CMD" != mvnd.sh ]; then
+    if "$MAVEN_HOME/bin/$MVN_CMD" --status >/dev/null 2>/dev/null; then
+      set_java_home || die "maven-mvnd requires JAVA_HOME"
+    else
+      MVN_CMD=mvnd.sh
+    fi
+  fi
+  unset MVNW_VERBOSE MVNW_USERNAME MVNW_PASSWORD MVNW_REPOURL || :
+  exec "$MAVEN_HOME/bin/$MVN_CMD" "$@" || die "cannot exec $MAVEN_HOME/bin/$MVN_CMD"
+}
 
 if [ -d "$MAVEN_HOME" ]; then
   verbose "found existing MAVEN_HOME at $MAVEN_HOME"
-  unset MVNW_VERBOSE MVNW_USERNAME MVNW_PASSWORD MVNW_REPOURL
-  exec "$MAVEN_HOME/bin/$MVN_CMD" "$@" || die "MAVEN_HOME is not valid: cannot exec $MAVEN_HOME/bin/mvn"
+  exec_maven "$@"
 fi
 
 case "${distributionUrl-}" in
 (*?-bin.zip) ;;
-(*) die "distributionUrl is not valid, must end with *-bin.zip, but found '${distributionUrl-}'" ;;
+(*?maven-mvnd-?*-?*.zip) ;;
+(*) die "distributionUrl is not valid, must match *-bin.zip or maven-mvnd-*.zip, but found '${distributionUrl-}'" ;;
 esac
 
 # prepare tmp dir
@@ -179,7 +219,11 @@ fi
 # If specified, validate the SHA-256 sum of the Maven distribution zip file
 if [ -n "$distributionSha256Sum" ]; then
   distributionSha256Result=false
-  if command -v sha256sum > /dev/null; then
+  if $_MVNW_USE_MVND; then
+    echo "Checksum validation is not supported for maven-mvnd." >&2
+    echo "Please install either command, or disable validation by removing 'distributionSha256Sum' from your maven-wrapper.properties." >&2
+    exit 1
+  elif command -v sha256sum > /dev/null; then
     if echo "$distributionSha256Sum  $TMP_DOWNLOAD_DIR/$distributionUrlName" | sha256sum -c > /dev/null 2>&1; then
       distributionSha256Result=true
     fi
@@ -188,8 +232,8 @@ if [ -n "$distributionSha256Sum" ]; then
       distributionSha256Result=true
     fi
   else
-    echo "Checksum validation was requested but neither 'sha256sum' or 'shasum' are available."
-    echo "Please install either command, or disable validation by removing 'distributionSha256Sum' from your maven-wrapper.properties."
+    echo "Checksum validation was requested but neither 'sha256sum' or 'shasum' are available." >&2
+    echo "Please install either command, or disable validation by removing 'distributionSha256Sum' from your maven-wrapper.properties." >&2
     exit 1
   fi
   if [ $distributionSha256Result = false ]; then
@@ -209,5 +253,4 @@ printf %s\\n "$distributionUrl" > "$TMP_DOWNLOAD_DIR/$distributionUrlNameMain/mv
 mv -- "$TMP_DOWNLOAD_DIR/$distributionUrlNameMain" "$MAVEN_HOME" || [ -d "$MAVEN_HOME" ] || die "fail to move MAVEN_HOME"
 
 clean || :
-unset MVNW_VERBOSE MVNW_USERNAME MVNW_PASSWORD MVNW_REPOURL || :
-exec "$MAVEN_HOME/bin/$MVN_CMD" "$@"
+exec_maven "$@"
